export const MESSAGES = {
  START_PROOF: "ZKP2P_PLUGIN_START_PROOF",
  CAPTURE_FROM_ACTIVE_TAB: "ZKP2P_PLUGIN_CAPTURE_FROM_ACTIVE_TAB",
  VERIFY_SELECTED_PAYMENT: "ZKP2P_PLUGIN_VERIFY_SELECTED_PAYMENT",
  PREVIEW_PROVING_INPUTS: "ZKP2P_PLUGIN_PREVIEW_PROVING_INPUTS",
  RUN_PROVING: "ZKP2P_PLUGIN_RUN_PROVING",
  SUBMIT_PROOF: "ZKP2P_PLUGIN_SUBMIT_PROOF",
  QUERY_STATUS: "ZKP2P_PLUGIN_QUERY_STATUS",
  QUERY_AGGREGATION: "ZKP2P_PLUGIN_QUERY_AGGREGATION",
  GET_SESSION: "ZKP2P_PLUGIN_GET_SESSION",
  RESET_SESSION: "ZKP2P_PLUGIN_RESET_SESSION",
  STATUS_EVENT: "ZKP2P_PLUGIN_STATUS_EVENT"
};

export const SESSION_STATUS = {
  IDLE: "idle",
  PENDING: "pending",
  WISE_OPENED: "wise_opened",
  CAPTURE_READY: "capture_ready",
  PROVING: "proving",
  PROOF_READY: "proof_ready",
  SUBMITTED: "submitted",
  VERIFIED: "verified",
  AGGREGATED: "aggregated",
  ERROR: "error"
};

export const VERIFICATION_MODE = "aggregation-kurier";
export const PROOF_SYSTEM = "ultrahonk";
